version: "3.9"

# Time Space – minimal stack (frontend + agent) with no database
services:
  frontend:
    container_name: timespace_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"           # Vite / Static site port
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_MAPBOX_ACCESS_TOKEN=${VITE_MAPBOX_ACCESS_TOKEN}
    depends_on:
      - backend
    networks:
      - timespace_net

  backend:
    container_name: timespace_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    networks:
      - timespace_net

networks:
  timespace_net:
    driver: bridge
